# Multiple VMs can be defined here
vms = [
	{
		:name            => 'dev',
		:box             => 'precise32',
		:url             => 'http://files.vagrantup.com/precise32.box',
		:memory          => '512',
		:forwarded_ports => [
			{:guest => 8080,  :host => 8080}
		],
		:synced_folders  => [
			{:host => './ansible', :guest => '/ansible'},
			{:host => '../diploma thesis/src', :guest => '/thesis'}
		]
	}
]

# Loop through vms array and create all VMs
Vagrant.configure("2") do |config|
	vms.each do |vm|
		config.vm.define vm[:name] do |vm_config|
			# Configure box settings
			vm_config.vm.box     = vm[:box]
			vm_config.vm.box_url = vm[:url]

			# Forward ports
			vm[:forwarded_ports].each do |port|
				vm_config.vm.network :forwarded_port, guest: port[:guest], host: port[:host]
			end

			# Set up synced folders
			vm[:synced_folders].each do |synced_folder|
				vm_config.vm.synced_folder synced_folder[:host], synced_folder[:guest]
			end

			# Configure VM parameters
			vm_config.vm.provider :virtualbox do |vb|
				vb.gui  = false
				vb.name = vm[:name]
				vb.customize ["modifyvm", :id, "--memory", vm[:memory] ]
			end

			# Setup Ansible
			vm_config.vm.provision :shell, 
				:inline => "sudo apt-get update " +
				           "&& sudo apt-get -y install python-software-properties " +
				           "&& sudo add-apt-repository -y ppa:rquillo/ansible " +
				           "&& sudo apt-get -y install ansible " +
				           "&& echo localhost > /etc/ansible/hosts " +
				           "&& sudo ansible-playbook /ansible/playbook.yml --connection=local"
		end
	end
end
