require 'fileutils'

desc 'build a pdf file'
task :build => ['build:pdf']

namespace :build do

	namespace :pdf do

		desc 'build with texliveonfly tp install missing packages'
		task :texliveonfly do
			system 'texliveonfly.py thesis.tex'
		end

		desc 'build with pplatex for prettier output'
		task :pplatex do
			system '/opt/pplatex-1.0-rc1/bin/pplatex -c lualatex -- -synctex=1 -interaction=nonstopmode -shell-escape thesis.tex'
		end

		task :biber do
			system 'biber --bibencoding=UTF8 thesis'
		end
	end

	desc 'build a pdf file (output: thesis.pdf)'
	task :pdf => ['pdf:texliveonfly', 'pdf:biber'] do
		system 'makeindex thesis.nlo -s nomencl.ist -o thesis.nls'
		Rake::Task["build:pdf:pplatex"].invoke
		FileUtils.cp 'thesis.pdf', '../Diplomarbeit - Lukas Reinfurt - Bootstrapping Provisioning Engines for On-demand Provisioning in Cloud Environments.pdf'
	end

end

desc 'removes pdf and temporary files'
task :clean do
	rm_f Dir['*.aux', '*.bbl', '*.bcf', '*.blg', '*.ilg', '*.lof', '*.log', '*.lol', '*.lot', '*.nlo', '*.nls', '*.out', '*.pdf', '*.pyg', '*.xml', '*.gz', '*.toc']
end

desc 'show this list (also "rake", "rake -T")'
task :default do
	system 'rake -T'
end
