- name: update apt
  apt: update_cache=yes

- name: set ANSIBLE_FORCE_COLOR
  lineinfile: dest=/etc/environment line='ANSIBLE_FORCE_COLOR="true"'

- name: WARNING!!! make ANSIBLE_FORCE_COLOR accessible for sudo user
  lineinfile: dest=/etc/sudoers line='Defaults env_keep +="ANSIBLE_FORCE_COLOR"'
